# Eigenvalues, eigenvectors


--------------
## 1. Eigenvalues and eigenvectors

<font color=green>**Definition.** Let $A$ be an $n\times n$ matrix.  A non-zero vector $x$ in $\mathbb{R}^n$ is called an **eigenvector** of $A$ such that:

<font color=green>$$Ax=\lambda x$$

<font color=green>for some scalar $\lambda$, which will be called **eigenvalue** corresponding to $x$.

<font color=green>The above can be rewritten as the following homogeneous equation: $(A-\lambda I_n)x = 0$

<font color=green>The trivial solution is $x=0$. To find the eigenvalues, you need the determinant of $A - \lambda I_n $ to be zero, i.e.
$$|A-\lambda I_n| = 0$$ 

<font color=green>Once you know the eigenvalues $\lambda$, you use $(A-\lambda I_n)x = 0$ to find the corresponding eigenvectors.

<font color=blue>**Example**. Consider the matrix $A = \left[\begin{matrix}  1 & 2 & 0 \\ 2 & 1 & 0 \\ 0 & 0 & 3\end{matrix}\right] $ along with the calculation $\left[\begin{matrix}  1 & 2 & 0 \\ 2 & 1 & 0 \\ 0 & 0 & 3\end{matrix}\right] \left[\begin{matrix}  1 \\  1 \\ 1\end{matrix}\right] =\left[\begin{matrix}  3 \\  3 \\ 3\end{matrix}\right]  $
Given this, which of the following statements are true?\
        a. 1 is an eigenvalue of $A$.\
        b. 2 is an eigenvalue of $A$.\
        c. 3 is an eigenvalue of $A$.\
        d. $\left[\begin{matrix}  5 \\  5 \\ 5\end{matrix}\right]$ is an eigenvector of $A$\
        e. $\left[\begin{matrix}  1 \\  1 \\ 1\end{matrix}\right]$ is an eigenvector of $A$
        

In [ ]:
#put your answer here

<font color=blue>**Example**. Find the eigenvalues of $A=\begin{bmatrix}
2 & 3  \\ 
3 & -6    
\end{bmatrix}$ and the corresponding eigenvectors by hand.

In [1]:
#put your answer here

Now we can use the numpy library to get the eigenvalues and eigenvectors. For example, 

```
A = np.matrix([[4,0,-2],[2,5,4],[0,0,5]])
eigvals, eigvecs = np.linalg.eig(A)
eigvals, eigvecs

```

<font color=blue> This time you can use numpy to calculate the eigenvalues and eigenvectors of $A$. Store the eigenvector associated with the smallest eigenvalue in a vector named ```v1``` and the eigenvector associated with the biggest eigenvalue in a vector named ```v2``` and **compare with the work you did by hand**. 

In [1]:
import numpy as np
import sympy as sym
A = np.matrix(...)
vals, vects = 

e1 = vals[0]
e2 = 

v1 = vects[:,0]
v2 = 

In [ ]:
v1 = sym.Matrix(A).eigenvects()[0][2][0]
v2 = sym.Matrix(A).eigenvects()[1][2][0]

**<font color=red>DO THIS:</font>** `sympy` can also calculate the eigenvectors/values using some of its own methods. Make $A$ into a sympy matrix and call the `.eigenvects()` methods on it. (Bonus: Try `.charpoly()` to retrieve the characteristic polynomial.)

In [ ]:
sym.init_printing()

In [ ]:
A_sym = sym.Matrix(A)
A_sym.charpoly()
A_sym.eigenvects()

**<font color=red>QUESTION:</font>**  Both **sympy** and **numpy** have their own way to produce the eigenvectors and eigenvalues. How are they are different?

In [ ]:
#Put your answer to the above question here.

----

## 2. Introduction to Markov Models


>In probability theory, a Markov model is a stochastic model used to model randomly changing systems. 
It is assumed that future states depend only on the current state, not on the events that occurred before it.
>
> <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Markovkate_01.svg/1126px-Markovkate_01.svg.png" alt="State space diagram. See text for description" width=25%>
> A diagram representing a two-state Markov process, with the states labelled E and A. 
Each number represents the probability of the Markov process changing from one state to another state, with the direction indicated by the arrow. 
For example, if the Markov process is in state A, then the probability it changes to state E is 0.4, while the probability it remains in state A is 0.6.


The above state model can be represented by a transition matrix. 

At each time step ($t$) the probability to move between states depends on the previous state $t-1$:

$$A_{t} = 0.6A_{t-1}+0.7E_{t-1}$$

$$E_{t} = 0.4A_{t-1}+0.3E_{t-1}$$

The above state model ($S_t = [A_t, E_t]^T$) can be represented in the following matrix notation:


$$S_t = PS_{t-1}$$


**<font color=red>DO THIS:</font>** Create a $2 \times 2$ matrix $\begin{array}{cc}
P =  
\begin{bmatrix}
    p_{A\rightarrow A} & p_{E\rightarrow A}  \\
    p_{A\rightarrow E} & p_{E\rightarrow E} 
\end{bmatrix}
\end{array}
$ representing the transition matrix for the above Markov space.

In [ ]:
%matplotlib inline
import matplotlib.pylab as plt
import numpy as np
import sympy as sym
sym.init_printing(use_unicode=True)

In [4]:
A = np.matrix(...)
sym.Matrix(A)

⎡0.6  0.7⎤
⎢        ⎥
⎣0.4  0.3⎦

Notice how the **columns in the matrix all add to one**. This is because all of the transition probabilities out of a matrix must add to 100 percent. 

A Markov matrix $P$ always has an **eigenvalue $1$**. All other eigenvalues are in absolute value smaller or equal to $1$.

### Example 1:

Now, consider the following house map with cats in each room...

At each time step, there is an equal probability of a cat staying in their current room or moving to a new room. 
If a cat chooses to leave a room, then there is an equal chance of that cat picking any of the doors in the room to leave. 

<img src="https://lh4.googleusercontent.com/CGFHfJgtrPu-2bZPhPul1ll8B3tqC1Vs8jRwnZ13v8MqRAagWhrSmJ0cznYIP3ePg5co5AVI8g=w712" width="50%">

**<font color=red>DO THIS :</font>** Try to draw a Markov chain (Markov matrix) for the above system of equations. Be prepared to share your diagram with the class. 

A Markov chain can be represented as a Markov transition model of the form $Px=b$. 
Where $P$ is your probability tranisition matrix, $x$ is the state before the transition and $b$ is the state after the transition.

**<font color=red>QUESTION:</font>** Generate a Markov transition model represented as a matrix $P$ of the form:
$$
\begin{array}{ccc}
& \text{Current Room}  \\
P =  &
\begin{bmatrix}
    p_{11} & p_{12} & p_{13} \\
    p_{21} & p_{22} & p_{23} \\
    p_{31} & p_{32} & p_{33} 
\end{bmatrix}
\end{array}
\text{Next Room}
$$

Where $p_{ij}$ are probability transitions of the cat moving between rooms (from room $j$ to room $i$):

In [5]:
P = np.matrix(...)
sym.Matrix(P)

⎡       0.5         0.333333333333333  0.25⎤
⎢                                          ⎥
⎢0.333333333333333         0.5         0.25⎥
⎢                                          ⎥
⎣0.166666666666667  0.166666666666667  0.5 ⎦

**<font color=red>QUESTION:</font>**  Let's assume that the system starts with; 6 cats in room 1, 15 cats in room 2, and 3 cats in room 3. On average, how many cats will be in each room after one time step (Store the values in a vector called ```current_state```)?

In [9]:
current_state = np.matrix([[6], ..., ...])

current_state = P*current_state
sym.Matrix(...)

⎡8.75 ⎤
⎢     ⎥
⎢10.25⎥
⎢     ⎥
⎣ 5.0 ⎦

**<font color=red>QUESTION:</font>** The following code will plot the expected number of cats as a function of time $t$.  When this system converges, what is the steady state?

In [11]:
#Define Start State
room1 = [6]
room2 = [15]
room3 = [3]

current_state = np.matrix([room1, room2, room3])

for i in range(100):
    #update Current State
    current_state = 
    
    #Store history for each room
    room1.append(current_state[0])
    room2.append(...)
    room3.append(...)
    
# plt.plot(room1, label="room1");
# plt.plot(room2, label="room2");
# plt.plot(room3, label="room3");
# plt.legend();
print(current_state)

[[9.]
 [9.]
 [6.]]


In [ ]:
qaz = np.matrix([1,2,3])
print(qaz)

In [ ]:
# Inspect the generated graph and put your answer to the above question here

---
**<font color=red>QUESTION:</font>**  Calculate the eigenvalues and eigenvectors of your $P$ transition matrix.  

In [6]:
eigval, eigvec = 
sym.Matrix(eigvec)

⎡-0.639602149066831   -0.707106781186547    -0.408248290463863⎤
⎢                                                             ⎥
⎢-0.639602149066831    0.707106781186548    -0.408248290463863⎥
⎢                                                             ⎥
⎣-0.426401432711221  -3.35034232347364e-16  0.816496580927726 ⎦

The eigenvector associated with the eigenvalue of 1 represents the **steady state** probability for our original transition matrix $P$.  

**<font color=red>DO THIS:</font>** make a new vector called ```steadystate``` from the eigenvector of your $P$ matrix with a eigenvalue of 1.

In [7]:
steadystate = eigvec[:,0]
steadystate

matrix([[-0.63960215],
        [-0.63960215],
        [-0.42640143]])

Since the ```steadystate``` vectors represent long term probabilities, they should sum to one (1).  However, many programming libraries (including numpy) return "normalized" eigenvectors to length of 1 (i.e. norm(e)==1). 

**<font color=red>DO THIS:</font>**  Correct for the normalization by multiplying the ```steadystate``` eigenvector by a constant such that the sum of the vector elements add to 1. 

In [12]:
steadystate = 
steadystate

matrix([[0.375],
        [0.375],
        [0.25 ]])

**<font color=red>DO THIS:</font>**  The steady state represents the proportion of cats that will be in each room, but since we know the initial number of cats, we can find how these cats arrange themselves in the steady state by multiplying `steadystate` by the total number of cats.  The resulting vector should be identical to the steady state in the above chart.

In [13]:
steadystate = 
steadystate

matrix([[9.],
        [9.],
        [6.]])

**<font color=red>QUESTION:</font>** Why does the sum of the numbers at every stage remain the same? 



###  Example 2

> A sports broadcaster wishes to predict how many Michigan residents prefer University of Michigan teams and how many prefer Michigan State teams. 
She noticed that, year after year, most people stick with their preferred team; however, about 5% of Michigan fans switch to Michigan State, and about 3% of Michigan State fans switch to Michigan each year. 
However, there is no noticeable difference in the state's population of 10 million's preference at large; in other words, it seems Michigan sports fans have reached a stationary distribution. What might that be?


**<font color=red>DO THIS:</font>** Try to draw a Markov chain for the above system of equations. Discuss your diagram with your classmates.

**<font color=red>QUESTION:</font>**  Write a system of linear equations that represents how the populations change each year. Check your equations by writing the matrix ```P``` for the probability transitions matrix in your equations. Make sure your first row/column represents MSU and the second row/column represents UofM. 

In [ ]:
P = 
sym.Matrix(P)

**<font color=red>QUESTION:</font>**   Use Numpy to calculate the eigenvalues and eigenvectors of your $P$ transition matrix.  

In [ ]:
eigval, eigvec =
print(eigval)
sym.Matrix(eigvec)

**<font color=red>QUESTION:</font>**   Assuming both teams start with 500,000 fans each (so 1,000,000 fans total), what is the steady state of this model? (I.e. in the long term how many Spartan and Wolverine fans will there be?).

In [ ]:
steadystate =     #correct the normalization
steadystate =     # mulptiply by the total number

spartans = steadystate[0]
wolverines = steadystate[1]